name: Extracting VerCode - NA

on:
  push:
    branches: [NA]
  pull_request:
    branches: [NA]
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/yamadamasato666/FGO-VerCode-extractor/NA/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v3

      - name: Execute main script
        run: python3 main.py

      - name: Commit & push changes to branch NA
        uses: actions-js/push@master
        with:
          force: true
          branch: "NA"
          github_token: ${{ secrets.TOKEN_REPO }}
